# TenEngineHelpers.cmake - 002-object (per docs/engine-build-module-convention.md)
# Build root: run cmake from this module dir (Engine/TenEngine-002-object) or from repo root if root adds this subdir.
# Dependencies: source only (add_subdirectory); 001-core via TENENGINE_001_CORE_DIR or ../TenEngine-001-core.

if(NOT TENENGINE_CMAKE_DIR)
  set(TENENGINE_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
endif()
include(${TENENGINE_CMAKE_DIR}/TenEngineModuleDependencies.cmake)

function(tenengine_resolve_dependency mod_id out_var)
  string(REPLACE "-" "_" u "${mod_id}")
  string(TOUPPER "${u}" U)
  set(opt_use_source "TENENGINE_${U}_USE_SOURCE")
  set(opt_dir "TENENGINE_${U}_DIR")
  if(NOT DEFINED ${opt_use_source})
    set(${opt_use_source} ON)
  endif()
  if(${opt_use_source})
    if(NOT DEFINED ${opt_dir})
      if(DEFINED TENENGINE_ROOT)
        set(${opt_dir} "${TENENGINE_ROOT}/TenEngine-${mod_id}")
      else()
        set(${opt_dir} "${CMAKE_CURRENT_SOURCE_DIR}/../TenEngine-${mod_id}")
      endif()
    endif()
    set(dep_dir "${${opt_dir}}")
    if(NOT EXISTS "${dep_dir}/CMakeLists.txt")
      message(FATAL_ERROR "TenEngine SOURCE dependency ${mod_id} not found at ${dep_dir}. Set TENENGINE_${U}_DIR or TENENGINE_ROOT.")
    endif()
    get_property(_already_added GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} SET)
    if(NOT _already_added)
      add_subdirectory("${dep_dir}" "${CMAKE_BINARY_DIR}/TenEngine_${mod_id}")
      set_property(GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} TRUE)
    endif()
    tenengine_module_id_to_target("${mod_id}" _target)
    set(${out_var} "${_target}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "002-object requires 001-core as SOURCE; PREBUILT not configured here.")
  endif()
endfunction()

function(tenengine_resolve_my_dependencies my_mod_id OUT_DEPS out_list_var)
  tenengine_get_deps("${my_mod_id}" _deps)
  set(_targets "")
  foreach(dep_id IN LISTS _deps)
    tenengine_resolve_dependency("${dep_id}" _t)
    list(APPEND _targets "${_t}")
  endforeach()
  set(${out_list_var} ${_targets} PARENT_SCOPE)
endfunction()

function(tenengine_add_module_test)
  cmake_parse_arguments(ARG "ENABLE_CTEST" "NAME;MODULE_TARGET" "SOURCES" ${ARGN})
  if(NOT ARG_NAME OR NOT ARG_MODULE_TARGET)
    message(FATAL_ERROR "tenengine_add_module_test requires NAME and MODULE_TARGET")
  endif()
  add_executable(${ARG_NAME} ${ARG_SOURCES})
  target_link_libraries(${ARG_NAME} PRIVATE ${ARG_MODULE_TARGET})
  if(ARG_ENABLE_CTEST)
    enable_testing()
    add_test(NAME ${ARG_NAME} COMMAND ${ARG_NAME})
  endif()
endfunction()
