# TenEngineHelpers.cmake - 028-texture module
if(NOT TENENGINE_CMAKE_DIR)
  set(TENENGINE_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
endif()
include(${TENENGINE_CMAKE_DIR}/TenEngineModuleDependencies.cmake)

function(tenengine_resolve_dependency mod_id out_var)
  string(REPLACE "-" "_" u "${mod_id}")
  string(TOUPPER "${u}" U)
  set(opt_dir "TENENGINE_${U}_DIR")
  if(NOT DEFINED ${opt_dir})
    if(DEFINED TENENGINE_ROOT)
      set(${opt_dir} "${TENENGINE_ROOT}/Engine/TenEngine-${mod_id}")
    else()
      get_filename_component(_CURRENT_DIR "${CMAKE_CURRENT_SOURCE_DIR}" DIRECTORY)
      get_filename_component(_ENGINE_DIR "${_CURRENT_DIR}" DIRECTORY)
      set(${opt_dir} "${_ENGINE_DIR}/TenEngine-${mod_id}")
    endif()
  endif()
  set(dep_dir "${${opt_dir}}")
  if(NOT EXISTS "${dep_dir}/CMakeLists.txt")
    message(FATAL_ERROR "TenEngine dependency ${mod_id} not found at ${dep_dir}. Set TENENGINE_${U}_DIR or TENENGINE_ROOT.")
  endif()
  get_property(_already_added GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} SET)
  if(NOT _already_added)
    add_subdirectory("${dep_dir}" "${CMAKE_BINARY_DIR}/TenEngine_${mod_id}")
    set_property(GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} TRUE)
  endif()
  tenengine_module_id_to_target("${mod_id}" _target)
  set(${out_var} "${_target}" PARENT_SCOPE)
endfunction()

function(tenengine_get_deps mod_id out_list_var)
  string(REPLACE "-" "_" u "${mod_id}")
  string(TOUPPER "${u}" U)
  set(var_name "TENENGINE_${U}_DEPS")
  if(DEFINED ${var_name})
    set(${out_list_var} ${${var_name}} PARENT_SCOPE)
  else()
    set(${out_list_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(tenengine_resolve_my_dependencies my_mod_id OUT_DEPS out_list_var)
  tenengine_get_deps("${my_mod_id}" _deps)
  set(_targets "")
  foreach(dep_id IN LISTS _deps)
    tenengine_resolve_dependency("${dep_id}" _t)
    list(APPEND _targets "${_t}")
  endforeach()
  set(${out_list_var} ${_targets} PARENT_SCOPE)
endfunction()
