# TenEngineHelpers.cmake
# Lives in every branch: TenEngine-XXX-Module/cmake/
# - Resolve dependency: SOURCE (add_subdirectory) or PREBUILT (find_package / DLL)
# - Add test/app with automatic transitive dependency (link module target only)
#
# Include: no main repo. Use own cmake or sibling upstream's cmake.
# - Root module (e.g. 001-core): set(TENENGINE_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake") then include(...)
# - Downstream (e.g. 002-object): set(TENENGINE_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../TenEngine-001-core/cmake") then include(...)

if(NOT TENENGINE_CMAKE_DIR)
  set(TENENGINE_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
endif()
include(${TENENGINE_CMAKE_DIR}/TenEngineModuleDependencies.cmake)

# TENENGINE_ROOT: parent dir of all worktrees (e.g. G:/AIHUMAN/WorkSpaceSDD). If unset, sibling ../ is used per dep.
# For each dependency module (e.g. 001-core):
#   TENENGINE_001_CORE_USE_SOURCE  ON = add_subdirectory (default), OFF = use prebuilt
#   TENENGINE_001_CORE_DIR        When USE_SOURCE: path to TenEngine-001-core (default ${TENENGINE_ROOT}/TenEngine-001-core or ../TenEngine-001-core)
#   TENENGINE_001_CORE_PREFIX     When USE_SOURCE=OFF: install prefix for find_package / DLL (or set CMAKE_PREFIX_PATH)

# Resolve one dependency: ensure the dependency target exists and return its name.
# Usage: tenengine_resolve_dependency("001-core" out_var)
# After call, ${out_var} is the target to use in target_link_libraries (e.g. te_core or TenEngine::Core).
function(tenengine_resolve_dependency mod_id out_var)
  string(REPLACE "-" "_" u "${mod_id}")
  string(TOUPPER "${u}" U)
  set(opt_use_source "TENENGINE_${U}_USE_SOURCE")
  set(opt_dir "TENENGINE_${U}_DIR")
  set(opt_prefix "TENENGINE_${U}_PREFIX")
  if(NOT DEFINED ${opt_use_source})
    set(${opt_use_source} ON)
  endif()
  if(${opt_use_source})
    if(NOT DEFINED ${opt_dir})
      if(DEFINED TENENGINE_ROOT)
        set(${opt_dir} "${TENENGINE_ROOT}/TenEngine-${mod_id}")
      else()
        set(${opt_dir} "${CMAKE_CURRENT_SOURCE_DIR}/../TenEngine-${mod_id}")
      endif()
    endif()
    set(dep_dir "${${opt_dir}}")
    if(NOT EXISTS "${dep_dir}/CMakeLists.txt")
      message(FATAL_ERROR "TenEngine SOURCE dependency ${mod_id} not found at ${dep_dir}. Set TENENGINE_${U}_DIR or TENENGINE_ROOT.")
    endif()
    get_property(_already_added GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} SET)
    if(NOT _already_added)
      # Set flag to skip dependency tests when adding upstream modules
      set(_old_skip_tests ${TENENGINE_SKIP_DEPENDENCY_TESTS})
      set(TENENGINE_SKIP_DEPENDENCY_TESTS ON)
      add_subdirectory("${dep_dir}" "${CMAKE_BINARY_DIR}/TenEngine_${mod_id}")
      set(TENENGINE_SKIP_DEPENDENCY_TESTS ${_old_skip_tests})
      set_property(GLOBAL PROPERTY TENENGINE_ADDED_${mod_id} TRUE)
    endif()
    tenengine_module_id_to_target("${mod_id}" _target)
    set(${out_var} "${_target}" PARENT_SCOPE)
  else()
    if(NOT DEFINED ${opt_prefix})
      set(${opt_prefix} "${TENENGINE_ROOT}/tenengine-install")
    endif()
    set(_prefix "${${opt_prefix}}")
    # Prebuilt: try find_package first; else create imported target from prefix (include + lib/dll).
    string(REGEX REPLACE "^[0-9]+-" "" _name_part "${mod_id}")
    string(REPLACE "-" "_" _target_suffix "${_name_part}")
    set(_target "te_${_target_suffix}")
    set(_package "TenEngine${_name_part}")
    string(TOLOWER "${_package}" _package_lower)
    find_package(${_package} QUIET HINTS "${_prefix}" NO_DEFAULT_PATH)
    if(${_package}_FOUND AND TARGET ${_package}::${_package})
      set(${out_var} "${_package}::${_package}" PARENT_SCOPE)
      return()
    endif()
    # Create imported target
    find_library(TENENGINE_${U}_LIBRARY NAMES te_${_target_suffix} tenengine_${_target_suffix} HINTS "${_prefix}/lib" "${_prefix}/bin" NO_DEFAULT_PATH)
    set(TENENGINE_${U}_INCLUDE_DIR "${_prefix}/include")
    if(NOT TENENGINE_${U}_LIBRARY)
      message(FATAL_ERROR "TenEngine PREBUILT dependency ${mod_id}: library not found under ${_prefix}. Set TENENGINE_${U}_PREFIX.")
    endif()
    if(NOT TARGET TenEngine::${_target_suffix})
      add_library(TenEngine::${_target_suffix} SHARED IMPORTED GLOBAL)
      set_target_properties(TenEngine::${_target_suffix} PROPERTIES
        IMPORTED_LOCATION "${TENENGINE_${U}_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${TENENGINE_${U}_INCLUDE_DIR}")
    endif()
    set(${out_var} "TenEngine::${_target_suffix}" PARENT_SCOPE)
  endif()
endfunction()

# Resolve all direct dependencies for module and return list of targets.
# Usage: tenengine_resolve_my_dependencies("002-object" OUT_DEPS out_list_var)
function(tenengine_resolve_my_dependencies my_mod_id OUT_DEPS out_list_var)
  tenengine_get_deps("${my_mod_id}" _deps)
  set(_targets "")
  foreach(dep_id IN LISTS _deps)
    tenengine_resolve_dependency("${dep_id}" _t)
    list(APPEND _targets "${_t}")
  endforeach()
  set(${out_list_var} ${_targets} PARENT_SCOPE)
endfunction()

# Add a test executable that links only the module target (transitive deps included). Optional: enable_testing + add_test.
# tenengine_add_module_test(NAME te_object_test MODULE_TARGET te_object SOURCES a.cpp b.cpp [ENABLE_CTEST])
function(tenengine_add_module_test)
  cmake_parse_arguments(ARG "ENABLE_CTEST" "NAME;MODULE_TARGET" "SOURCES" ${ARGN})
  if(NOT ARG_NAME OR NOT ARG_MODULE_TARGET)
    message(FATAL_ERROR "tenengine_add_module_test requires NAME and MODULE_TARGET")
  endif()
  add_executable(${ARG_NAME} ${ARG_SOURCES})
  target_link_libraries(${ARG_NAME} PRIVATE ${ARG_MODULE_TARGET})
  if(ARG_ENABLE_CTEST)
    enable_testing()
    add_test(NAME ${ARG_NAME} COMMAND ${ARG_NAME})
  endif()
endfunction()

# Add an application executable that links only the module target (transitive deps included).
# tenengine_add_module_app(NAME my_tool MODULE_TARGET te_object SOURCES main.cpp)
function(tenengine_add_module_app)
  cmake_parse_arguments(ARG "" "NAME;MODULE_TARGET" "SOURCES" ${ARGN})
  if(NOT ARG_NAME OR NOT ARG_MODULE_TARGET)
    message(FATAL_ERROR "tenengine_add_module_app requires NAME and MODULE_TARGET")
  endif()
  add_executable(${ARG_NAME} ${ARG_SOURCES})
  target_link_libraries(${ARG_NAME} PRIVATE ${ARG_MODULE_TARGET})
endfunction()
